[package]
name = "ffffff"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.9"
sha2 = "0.10.9"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
zerocopy = "0.8.27"
zerocopy-derive = "0.8.27"
